# SERVER

#server.servlet.context-path=/org-media-api
server.port = 8484
spring.main.allow-bean-definition-overriding=true
#spring.jackson.serialization.INDENT_OUTPUT= true
#spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

#EXCEPTION HANDLER
server.error.whitelabel.enabled=false
spring.mvc.throw-exception-if-no-handler-found=true
spring.resources.add-mappings=false

#LOG
# logging.pattern.file= "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
logging.level.root=WARN
logging.level.com.org.media=DEBUG
logging.level.org.springframework.web=WARN
logging.file.path=/opt/deploy/dreamcareer/media
logging.file.name=logs/itdream-auth.log
logging.file=${catalina.home}/logs/spam.log

# config size upload
spring.servlet.multipart.max-file-size=1000MB
spring.servlet.multipart.max-request-size=1000MB

spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.hibernate.ddl-auto=none


#APP CONFIG
qrauth.auth.signing.key=T7PfKrPGvK

# Async Config
thread.pool.size=10
thread.pool.queue.size=150

#upload dir
file.upload-dir=/uploads

# Keystore config
certificate.keystore=classpath:keys/keystore.p12
certificate.alias=itdreamcert
certificate.storepass=ITDream2025@
certificate.keypass=ITDream2025@